services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WATCHFILES_FORCE_POLLING=1
    ports:
      - "8000:8000"
    volumes:
      - ./broker:/app/broker
      - ./data:/app/data
    command: [
      "uvicorn",
      "broker.api.main:app",
      "--host","0.0.0.0",
      "--port","8000",
      "--reload",
      "--reload-include","*.html",
      "--reload-include","*.js",
      "--reload-include","*.css"
    ]
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/healthz').getcode()==200 else 1)"]
      interval: 30s
      timeout: 5s
      retries: 3
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
